# Generated by Django 4.2.1 on 2023-06-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esterilizado',
            fields=[
                ('id_esterilizado', models.AutoField(db_column='idEsterilizado', primary_key=True, serialize=False)),
                ('esterilizado', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nro_chip', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('esterilizado', models.ForeignKey(db_column='idEsterilizado', on_delete=django.db.models.deletion.CASCADE, to='home.esterilizado')),
                ('id_sexo', models.ForeignKey(db_column='idSexo', on_delete=django.db.models.deletion.CASCADE, to='home.sexo')),
            ],
        ),
    ]
